// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_adult_mosquito_model
Rcpp::XPtr<AdultMosquitoModel> create_adult_mosquito_model(Rcpp::XPtr<AquaticMosquitoModel> growth_model, double mu, double tau, double susceptible, double foim);
RcppExport SEXP _malariasimulationGD_create_adult_mosquito_model(SEXP growth_modelSEXP, SEXP muSEXP, SEXP tauSEXP, SEXP susceptibleSEXP, SEXP foimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AquaticMosquitoModel> >::type growth_model(growth_modelSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type susceptible(susceptibleSEXP);
    Rcpp::traits::input_parameter< double >::type foim(foimSEXP);
    rcpp_result_gen = Rcpp::wrap(create_adult_mosquito_model(growth_model, mu, tau, susceptible, foim));
    return rcpp_result_gen;
END_RCPP
}
// adult_mosquito_model_update
void adult_mosquito_model_update(Rcpp::XPtr<AdultMosquitoModel> model, double mu, double foim, double susceptible, double f);
RcppExport SEXP _malariasimulationGD_adult_mosquito_model_update(SEXP modelSEXP, SEXP muSEXP, SEXP foimSEXP, SEXP susceptibleSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AdultMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type foim(foimSEXP);
    Rcpp::traits::input_parameter< double >::type susceptible(susceptibleSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    adult_mosquito_model_update(model, mu, foim, susceptible, f);
    return R_NilValue;
END_RCPP
}
// adult_mosquito_model_save_state
std::vector<double> adult_mosquito_model_save_state(Rcpp::XPtr<AdultMosquitoModel> model);
RcppExport SEXP _malariasimulationGD_adult_mosquito_model_save_state(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AdultMosquitoModel> >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(adult_mosquito_model_save_state(model));
    return rcpp_result_gen;
END_RCPP
}
// adult_mosquito_model_restore_state
void adult_mosquito_model_restore_state(Rcpp::XPtr<AdultMosquitoModel> model, std::vector<double> state);
RcppExport SEXP _malariasimulationGD_adult_mosquito_model_restore_state(SEXP modelSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AdultMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type state(stateSEXP);
    adult_mosquito_model_restore_state(model, state);
    return R_NilValue;
END_RCPP
}
// create_adult_solver
Rcpp::XPtr<Solver> create_adult_solver(Rcpp::XPtr<AdultMosquitoModel> model, std::vector<double> init, double r_tol, double a_tol, size_t max_steps);
RcppExport SEXP _malariasimulationGD_create_adult_solver(SEXP modelSEXP, SEXP initSEXP, SEXP r_tolSEXP, SEXP a_tolSEXP, SEXP max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AdultMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type r_tol(r_tolSEXP);
    Rcpp::traits::input_parameter< double >::type a_tol(a_tolSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_steps(max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_adult_solver(model, init, r_tol, a_tol, max_steps));
    return rcpp_result_gen;
END_RCPP
}
// create_aquatic_mosquito_model
Rcpp::XPtr<AquaticMosquitoModel> create_aquatic_mosquito_model(double beta, double de, double mue, Rcpp::XPtr<Timeseries> k_timeseries, double gamma, double dl, double mul, double dp, double mup, double total_M, bool model_seasonality, double g0, std::vector<double> g, std::vector<double> h, double R_bar, double mum, double f, double rainfall_floor);
RcppExport SEXP _malariasimulationGD_create_aquatic_mosquito_model(SEXP betaSEXP, SEXP deSEXP, SEXP mueSEXP, SEXP k_timeseriesSEXP, SEXP gammaSEXP, SEXP dlSEXP, SEXP mulSEXP, SEXP dpSEXP, SEXP mupSEXP, SEXP total_MSEXP, SEXP model_seasonalitySEXP, SEXP g0SEXP, SEXP gSEXP, SEXP hSEXP, SEXP R_barSEXP, SEXP mumSEXP, SEXP fSEXP, SEXP rainfall_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type de(deSEXP);
    Rcpp::traits::input_parameter< double >::type mue(mueSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<Timeseries> >::type k_timeseries(k_timeseriesSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type dl(dlSEXP);
    Rcpp::traits::input_parameter< double >::type mul(mulSEXP);
    Rcpp::traits::input_parameter< double >::type dp(dpSEXP);
    Rcpp::traits::input_parameter< double >::type mup(mupSEXP);
    Rcpp::traits::input_parameter< double >::type total_M(total_MSEXP);
    Rcpp::traits::input_parameter< bool >::type model_seasonality(model_seasonalitySEXP);
    Rcpp::traits::input_parameter< double >::type g0(g0SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type g(gSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type R_bar(R_barSEXP);
    Rcpp::traits::input_parameter< double >::type mum(mumSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type rainfall_floor(rainfall_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(create_aquatic_mosquito_model(beta, de, mue, k_timeseries, gamma, dl, mul, dp, mup, total_M, model_seasonality, g0, g, h, R_bar, mum, f, rainfall_floor));
    return rcpp_result_gen;
END_RCPP
}
// aquatic_mosquito_model_update
void aquatic_mosquito_model_update(Rcpp::XPtr<AquaticMosquitoModel> model, double total_M, double f, double mum);
RcppExport SEXP _malariasimulationGD_aquatic_mosquito_model_update(SEXP modelSEXP, SEXP total_MSEXP, SEXP fSEXP, SEXP mumSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AquaticMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type total_M(total_MSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type mum(mumSEXP);
    aquatic_mosquito_model_update(model, total_M, f, mum);
    return R_NilValue;
END_RCPP
}
// aquatic_mosquito_model_set_egg_proportions
void aquatic_mosquito_model_set_egg_proportions(Rcpp::XPtr<AquaticMosquitoModel> model, std::vector<double> egg_proportions);
RcppExport SEXP _malariasimulationGD_aquatic_mosquito_model_set_egg_proportions(SEXP modelSEXP, SEXP egg_proportionsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AquaticMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type egg_proportions(egg_proportionsSEXP);
    aquatic_mosquito_model_set_egg_proportions(model, egg_proportions);
    return R_NilValue;
END_RCPP
}
// create_aquatic_solver
Rcpp::XPtr<Solver> create_aquatic_solver(Rcpp::XPtr<AquaticMosquitoModel> model, std::vector<double> init, double r_tol, double a_tol, size_t max_steps);
RcppExport SEXP _malariasimulationGD_create_aquatic_solver(SEXP modelSEXP, SEXP initSEXP, SEXP r_tolSEXP, SEXP a_tolSEXP, SEXP max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AquaticMosquitoModel> >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type r_tol(r_tolSEXP);
    Rcpp::traits::input_parameter< double >::type a_tol(a_tolSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_steps(max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_aquatic_solver(model, init, r_tol, a_tol, max_steps));
    return rcpp_result_gen;
END_RCPP
}
// ento_engine_create
SEXP ento_engine_create(int nNodes, int nG, int nE, int nL, int nP, arma::ucube egg_ix, arma::ucube larv_ix, arma::ucube pup_ix, arma::umat male_ix, arma::umat unm_ix, arma::umat fem_ix, double rE, double rL, double rP, arma::vec muE, arma::vec muL, arma::vec muP, arma::vec muM, arma::vec muF, bool log_dd, arma::vec K, arma::vec gamma_dd, double beta, double nu, arma::vec omega, arma::vec phi_cube, arma::vec xiF, arma::vec xiM, arma::mat eta, arma::mat B_mat, bool has_move, arma::mat move_probs_dense, arma::vec move_rates, arma::vec muM_node_base, arma::vec muF_node_base, double tol, int nState);
RcppExport SEXP _malariasimulationGD_ento_engine_create(SEXP nNodesSEXP, SEXP nGSEXP, SEXP nESEXP, SEXP nLSEXP, SEXP nPSEXP, SEXP egg_ixSEXP, SEXP larv_ixSEXP, SEXP pup_ixSEXP, SEXP male_ixSEXP, SEXP unm_ixSEXP, SEXP fem_ixSEXP, SEXP rESEXP, SEXP rLSEXP, SEXP rPSEXP, SEXP muESEXP, SEXP muLSEXP, SEXP muPSEXP, SEXP muMSEXP, SEXP muFSEXP, SEXP log_ddSEXP, SEXP KSEXP, SEXP gamma_ddSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP omegaSEXP, SEXP phi_cubeSEXP, SEXP xiFSEXP, SEXP xiMSEXP, SEXP etaSEXP, SEXP B_matSEXP, SEXP has_moveSEXP, SEXP move_probs_denseSEXP, SEXP move_ratesSEXP, SEXP muM_node_baseSEXP, SEXP muF_node_baseSEXP, SEXP tolSEXP, SEXP nStateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nNodes(nNodesSEXP);
    Rcpp::traits::input_parameter< int >::type nG(nGSEXP);
    Rcpp::traits::input_parameter< int >::type nE(nESEXP);
    Rcpp::traits::input_parameter< int >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type egg_ix(egg_ixSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type larv_ix(larv_ixSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type pup_ix(pup_ixSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type male_ix(male_ixSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type unm_ix(unm_ixSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type fem_ix(fem_ixSEXP);
    Rcpp::traits::input_parameter< double >::type rE(rESEXP);
    Rcpp::traits::input_parameter< double >::type rL(rLSEXP);
    Rcpp::traits::input_parameter< double >::type rP(rPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muE(muESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muL(muLSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muP(muPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM(muMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF(muFSEXP);
    Rcpp::traits::input_parameter< bool >::type log_dd(log_ddSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_dd(gamma_ddSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_cube(phi_cubeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xiF(xiFSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xiM(xiMSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B_mat(B_matSEXP);
    Rcpp::traits::input_parameter< bool >::type has_move(has_moveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type move_probs_dense(move_probs_denseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type move_rates(move_ratesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM_node_base(muM_node_baseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF_node_base(muF_node_baseSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type nState(nStateSEXP);
    rcpp_result_gen = Rcpp::wrap(ento_engine_create(nNodes, nG, nE, nL, nP, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix, rE, rL, rP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, nState));
    return rcpp_result_gen;
END_RCPP
}
// ento_engine_set_runtime
void ento_engine_set_runtime(SEXP engine_ptr, arma::vec beta_vec, arma::vec muM, arma::vec muF, arma::vec K, arma::vec gamma_dd);
RcppExport SEXP _malariasimulationGD_ento_engine_set_runtime(SEXP engine_ptrSEXP, SEXP beta_vecSEXP, SEXP muMSEXP, SEXP muFSEXP, SEXP KSEXP, SEXP gamma_ddSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM(muMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF(muFSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_dd(gamma_ddSEXP);
    ento_engine_set_runtime(engine_ptr, beta_vec, muM, muF, K, gamma_dd);
    return R_NilValue;
END_RCPP
}
// ento_engine_set_seasonal_K
void ento_engine_set_seasonal_K(SEXP engine_ptr, int tmax_seasonal, Rcpp::Nullable<Rcpp::NumericVector> K_tbl_r);
RcppExport SEXP _malariasimulationGD_ento_engine_set_seasonal_K(SEXP engine_ptrSEXP, SEXP tmax_seasonalSEXP, SEXP K_tbl_rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type tmax_seasonal(tmax_seasonalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type K_tbl_r(K_tbl_rSEXP);
    ento_engine_set_seasonal_K(engine_ptr, tmax_seasonal, K_tbl_r);
    return R_NilValue;
END_RCPP
}
// ento_engine_dxdt
arma::vec ento_engine_dxdt(SEXP engine_ptr, double t, arma::vec state);
RcppExport SEXP _malariasimulationGD_ento_engine_dxdt(SEXP engine_ptrSEXP, SEXP tSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(ento_engine_dxdt(engine_ptr, t, state));
    return rcpp_result_gen;
END_RCPP
}
// create_ento_solver
Rcpp::XPtr<Solver> create_ento_solver(SEXP engine_ptr, std::vector<double> init, double r_tol, double a_tol, size_t max_steps);
RcppExport SEXP _malariasimulationGD_create_ento_solver(SEXP engine_ptrSEXP, SEXP initSEXP, SEXP r_tolSEXP, SEXP a_tolSEXP, SEXP max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type r_tol(r_tolSEXP);
    Rcpp::traits::input_parameter< double >::type a_tol(a_tolSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_steps(max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ento_solver(engine_ptr, init, r_tol, a_tol, max_steps));
    return rcpp_result_gen;
END_RCPP
}
// ento_engine_set_native
void ento_engine_set_native(SEXP engine_ptr);
RcppExport SEXP _malariasimulationGD_ento_engine_set_native(SEXP engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    ento_engine_set_native(engine_ptr);
    return R_NilValue;
END_RCPP
}
// ento_engine_clear_native
void ento_engine_clear_native();
RcppExport SEXP _malariasimulationGD_ento_engine_clear_native() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    ento_engine_clear_native();
    return R_NilValue;
END_RCPP
}
// epi_engine_create
SEXP epi_engine_create(int nNodes, int nM, int nG, int nE, int nL, int nP, int nEIP, int model_type, arma::ucube egg_ix, arma::ucube larv_ix, arma::ucube pup_ix, arma::umat male_ix, arma::umat unm_ix, Rcpp::IntegerVector fem_ix_flat, double rE, double rL, double rP, double rEIP, arma::vec muE, arma::vec muL, arma::vec muP, arma::vec muM, arma::vec muF, bool log_dd, arma::vec K, arma::vec gamma_dd, double beta, double nu, arma::vec omega, arma::vec phi_cube, arma::vec xiF, arma::vec xiM, arma::mat eta, arma::mat B_mat, bool has_move, arma::mat move_probs_dense, arma::vec move_rates, arma::vec muM_node_base, arma::vec muF_node_base, double tol, Rcpp::Nullable<Rcpp::NumericVector> c_vec_r, Rcpp::Nullable<Rcpp::NumericVector> b_vec_r, arma::vec a_vec, double muH_param, double r_param, double delta_param, Rcpp::Nullable<Rcpp::NumericVector> cT_vec_r, Rcpp::Nullable<Rcpp::NumericVector> cD_vec_r, Rcpp::Nullable<Rcpp::NumericVector> cU_vec_r, Rcpp::Nullable<Rcpp::NumericVector> W_age_r, double d1, Rcpp::NumericVector fd_r, double ID0, double kd, double gamma1_imp, Rcpp::IntegerVector mosy_nodes_r, Rcpp::IntegerVector human_nodes_r, Rcpp::IntegerVector hS_ix_r, Rcpp::IntegerVector hI_ix_r, Rcpp::IntegerVector hE_ix_r, Rcpp::IntegerVector hR_ix_r, bool has_hmove, arma::mat h_move_probs_dense, arma::vec h_move_rates, int nState);
RcppExport SEXP _malariasimulationGD_epi_engine_create(SEXP nNodesSEXP, SEXP nMSEXP, SEXP nGSEXP, SEXP nESEXP, SEXP nLSEXP, SEXP nPSEXP, SEXP nEIPSEXP, SEXP model_typeSEXP, SEXP egg_ixSEXP, SEXP larv_ixSEXP, SEXP pup_ixSEXP, SEXP male_ixSEXP, SEXP unm_ixSEXP, SEXP fem_ix_flatSEXP, SEXP rESEXP, SEXP rLSEXP, SEXP rPSEXP, SEXP rEIPSEXP, SEXP muESEXP, SEXP muLSEXP, SEXP muPSEXP, SEXP muMSEXP, SEXP muFSEXP, SEXP log_ddSEXP, SEXP KSEXP, SEXP gamma_ddSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP omegaSEXP, SEXP phi_cubeSEXP, SEXP xiFSEXP, SEXP xiMSEXP, SEXP etaSEXP, SEXP B_matSEXP, SEXP has_moveSEXP, SEXP move_probs_denseSEXP, SEXP move_ratesSEXP, SEXP muM_node_baseSEXP, SEXP muF_node_baseSEXP, SEXP tolSEXP, SEXP c_vec_rSEXP, SEXP b_vec_rSEXP, SEXP a_vecSEXP, SEXP muH_paramSEXP, SEXP r_paramSEXP, SEXP delta_paramSEXP, SEXP cT_vec_rSEXP, SEXP cD_vec_rSEXP, SEXP cU_vec_rSEXP, SEXP W_age_rSEXP, SEXP d1SEXP, SEXP fd_rSEXP, SEXP ID0SEXP, SEXP kdSEXP, SEXP gamma1_impSEXP, SEXP mosy_nodes_rSEXP, SEXP human_nodes_rSEXP, SEXP hS_ix_rSEXP, SEXP hI_ix_rSEXP, SEXP hE_ix_rSEXP, SEXP hR_ix_rSEXP, SEXP has_hmoveSEXP, SEXP h_move_probs_denseSEXP, SEXP h_move_ratesSEXP, SEXP nStateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nNodes(nNodesSEXP);
    Rcpp::traits::input_parameter< int >::type nM(nMSEXP);
    Rcpp::traits::input_parameter< int >::type nG(nGSEXP);
    Rcpp::traits::input_parameter< int >::type nE(nESEXP);
    Rcpp::traits::input_parameter< int >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< int >::type nEIP(nEIPSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type egg_ix(egg_ixSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type larv_ix(larv_ixSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type pup_ix(pup_ixSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type male_ix(male_ixSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type unm_ix(unm_ixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type fem_ix_flat(fem_ix_flatSEXP);
    Rcpp::traits::input_parameter< double >::type rE(rESEXP);
    Rcpp::traits::input_parameter< double >::type rL(rLSEXP);
    Rcpp::traits::input_parameter< double >::type rP(rPSEXP);
    Rcpp::traits::input_parameter< double >::type rEIP(rEIPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muE(muESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muL(muLSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muP(muPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM(muMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF(muFSEXP);
    Rcpp::traits::input_parameter< bool >::type log_dd(log_ddSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_dd(gamma_ddSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_cube(phi_cubeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xiF(xiFSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xiM(xiMSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B_mat(B_matSEXP);
    Rcpp::traits::input_parameter< bool >::type has_move(has_moveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type move_probs_dense(move_probs_denseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type move_rates(move_ratesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM_node_base(muM_node_baseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF_node_base(muF_node_baseSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type c_vec_r(c_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type b_vec_r(b_vec_rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_vec(a_vecSEXP);
    Rcpp::traits::input_parameter< double >::type muH_param(muH_paramSEXP);
    Rcpp::traits::input_parameter< double >::type r_param(r_paramSEXP);
    Rcpp::traits::input_parameter< double >::type delta_param(delta_paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cT_vec_r(cT_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cD_vec_r(cD_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cU_vec_r(cU_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type W_age_r(W_age_rSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fd_r(fd_rSEXP);
    Rcpp::traits::input_parameter< double >::type ID0(ID0SEXP);
    Rcpp::traits::input_parameter< double >::type kd(kdSEXP);
    Rcpp::traits::input_parameter< double >::type gamma1_imp(gamma1_impSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mosy_nodes_r(mosy_nodes_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type human_nodes_r(human_nodes_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hS_ix_r(hS_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hI_ix_r(hI_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hE_ix_r(hE_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hR_ix_r(hR_ix_rSEXP);
    Rcpp::traits::input_parameter< bool >::type has_hmove(has_hmoveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type h_move_probs_dense(h_move_probs_denseSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h_move_rates(h_move_ratesSEXP);
    Rcpp::traits::input_parameter< int >::type nState(nStateSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_engine_create(nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix_flat, rE, rL, rP, rEIP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, c_vec_r, b_vec_r, a_vec, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_dense, h_move_rates, nState));
    return rcpp_result_gen;
END_RCPP
}
// epi_engine_set_seasonal
void epi_engine_set_seasonal(SEXP engine_ptr, int tmax_seasonal, Rcpp::Nullable<Rcpp::NumericVector> beta_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> nu_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qE_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qL_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qEIP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muE_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muL_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muM_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muF_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> K_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> gamma_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> a_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muH_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> r_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> delta_tbl_r);
RcppExport SEXP _malariasimulationGD_epi_engine_set_seasonal(SEXP engine_ptrSEXP, SEXP tmax_seasonalSEXP, SEXP beta_tbl_rSEXP, SEXP nu_tbl_rSEXP, SEXP qE_tbl_rSEXP, SEXP qL_tbl_rSEXP, SEXP qP_tbl_rSEXP, SEXP qEIP_tbl_rSEXP, SEXP muE_tbl_rSEXP, SEXP muL_tbl_rSEXP, SEXP muP_tbl_rSEXP, SEXP muM_tbl_rSEXP, SEXP muF_tbl_rSEXP, SEXP K_tbl_rSEXP, SEXP gamma_tbl_rSEXP, SEXP a_tbl_rSEXP, SEXP muH_tbl_rSEXP, SEXP r_tbl_rSEXP, SEXP delta_tbl_rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type tmax_seasonal(tmax_seasonalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_tbl_r(beta_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type nu_tbl_r(nu_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qE_tbl_r(qE_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qL_tbl_r(qL_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qP_tbl_r(qP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qEIP_tbl_r(qEIP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muE_tbl_r(muE_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muL_tbl_r(muL_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muP_tbl_r(muP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muM_tbl_r(muM_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muF_tbl_r(muF_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type K_tbl_r(K_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type gamma_tbl_r(gamma_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type a_tbl_r(a_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muH_tbl_r(muH_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type r_tbl_r(r_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type delta_tbl_r(delta_tbl_rSEXP);
    epi_engine_set_seasonal(engine_ptr, tmax_seasonal, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r);
    return R_NilValue;
END_RCPP
}
// epi_engine_set_native
void epi_engine_set_native(SEXP engine_ptr);
RcppExport SEXP _malariasimulationGD_epi_engine_set_native(SEXP engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    epi_engine_set_native(engine_ptr);
    return R_NilValue;
END_RCPP
}
// epi_engine_clear_native
void epi_engine_clear_native();
RcppExport SEXP _malariasimulationGD_epi_engine_clear_native() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    epi_engine_clear_native();
    return R_NilValue;
END_RCPP
}
// epi_engine_set_runtime
void epi_engine_set_runtime(SEXP engine_ptr, arma::vec beta, arma::vec muM, arma::vec muF, arma::vec K, arma::vec gamma_dd, arma::vec a_vec);
RcppExport SEXP _malariasimulationGD_epi_engine_set_runtime(SEXP engine_ptrSEXP, SEXP betaSEXP, SEXP muMSEXP, SEXP muFSEXP, SEXP KSEXP, SEXP gamma_ddSEXP, SEXP a_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muM(muMSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muF(muFSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_dd(gamma_ddSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_vec(a_vecSEXP);
    epi_engine_set_runtime(engine_ptr, beta, muM, muF, K, gamma_dd, a_vec);
    return R_NilValue;
END_RCPP
}
// epi_engine_set_human_state
void epi_engine_set_human_state(Rcpp::NumericVector h_state, int na);
RcppExport SEXP _malariasimulationGD_epi_engine_set_human_state(SEXP h_stateSEXP, SEXP naSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h_state(h_stateSEXP);
    Rcpp::traits::input_parameter< int >::type na(naSEXP);
    epi_engine_set_human_state(h_state, na);
    return R_NilValue;
END_RCPP
}
// epi_engine_dxdt
arma::vec epi_engine_dxdt(SEXP engine_ptr, double t, arma::vec state);
RcppExport SEXP _malariasimulationGD_epi_engine_dxdt(SEXP engine_ptrSEXP, SEXP tSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(epi_engine_dxdt(engine_ptr, t, state));
    return rcpp_result_gen;
END_RCPP
}
// create_epi_solver
Rcpp::XPtr<Solver> create_epi_solver(SEXP engine_ptr, std::vector<double> init, double r_tol, double a_tol, size_t max_steps);
RcppExport SEXP _malariasimulationGD_create_epi_solver(SEXP engine_ptrSEXP, SEXP initSEXP, SEXP r_tolSEXP, SEXP a_tolSEXP, SEXP max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type init(initSEXP);
    Rcpp::traits::input_parameter< double >::type r_tol(r_tolSEXP);
    Rcpp::traits::input_parameter< double >::type a_tol(a_tolSEXP);
    Rcpp::traits::input_parameter< size_t >::type max_steps(max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_epi_solver(engine_ptr, init, r_tol, a_tol, max_steps));
    return rcpp_result_gen;
END_RCPP
}
// carrying_capacity
double carrying_capacity(const size_t timestep, const bool model_seasonality, const double g0, const std::vector<double>& g, const std::vector<double>& h, const double K0, const double R_bar, const double rainfall_floor);
RcppExport SEXP _malariasimulationGD_carrying_capacity(SEXP timestepSEXP, SEXP model_seasonalitySEXP, SEXP g0SEXP, SEXP gSEXP, SEXP hSEXP, SEXP K0SEXP, SEXP R_barSEXP, SEXP rainfall_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const size_t >::type timestep(timestepSEXP);
    Rcpp::traits::input_parameter< const bool >::type model_seasonality(model_seasonalitySEXP);
    Rcpp::traits::input_parameter< const double >::type g0(g0SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< const double >::type R_bar(R_barSEXP);
    Rcpp::traits::input_parameter< const double >::type rainfall_floor(rainfall_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(carrying_capacity(timestep, model_seasonality, g0, g, h, K0, R_bar, rainfall_floor));
    return rcpp_result_gen;
END_RCPP
}
// eggs_laid
double eggs_laid(double beta, double mu, double f);
RcppExport SEXP _malariasimulationGD_eggs_laid(SEXP betaSEXP, SEXP muSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(eggs_laid(beta, mu, f));
    return rcpp_result_gen;
END_RCPP
}
// rainfall
double rainfall(const size_t t, const double g0, const std::vector<double>& g, const std::vector<double>& h, const double floor);
RcppExport SEXP _malariasimulationGD_rainfall(SEXP tSEXP, SEXP g0SEXP, SEXP gSEXP, SEXP hSEXP, SEXP floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const size_t >::type t(tSEXP);
    Rcpp::traits::input_parameter< const double >::type g0(g0SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double >::type floor(floorSEXP);
    rcpp_result_gen = Rcpp::wrap(rainfall(t, g0, g, h, floor));
    return rcpp_result_gen;
END_RCPP
}
// exponential_process_cpp
Rcpp::XPtr<process_t> exponential_process_cpp(Rcpp::XPtr<DoubleVariable> variable, const double rate);
RcppExport SEXP _malariasimulationGD_exponential_process_cpp(SEXP variableSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<DoubleVariable> >::type variable(variableSEXP);
    Rcpp::traits::input_parameter< const double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_process_cpp(variable, rate));
    return rcpp_result_gen;
END_RCPP
}
// solver_get_states
std::vector<double> solver_get_states(Rcpp::XPtr<Solver> solver);
RcppExport SEXP _malariasimulationGD_solver_get_states(SEXP solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Solver> >::type solver(solverSEXP);
    rcpp_result_gen = Rcpp::wrap(solver_get_states(solver));
    return rcpp_result_gen;
END_RCPP
}
// solver_set_states
void solver_set_states(Rcpp::XPtr<Solver> solver, double t, std::vector<double> state);
RcppExport SEXP _malariasimulationGD_solver_set_states(SEXP solverSEXP, SEXP tSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Solver> >::type solver(solverSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type state(stateSEXP);
    solver_set_states(solver, t, state);
    return R_NilValue;
END_RCPP
}
// solver_step
void solver_step(Rcpp::XPtr<Solver> solver);
RcppExport SEXP _malariasimulationGD_solver_step(SEXP solverSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Solver> >::type solver(solverSEXP);
    solver_step(solver);
    return R_NilValue;
END_RCPP
}
// stoch_epi_engine_create
SEXP stoch_epi_engine_create(int nNodes, int nM, int nG, int nE, int nL, int nP, int nEIP, int model_type, Rcpp::IntegerVector egg_ix_r, Rcpp::IntegerVector larv_ix_r, Rcpp::IntegerVector pup_ix_r, Rcpp::IntegerVector male_ix_r, Rcpp::IntegerVector unm_ix_r, Rcpp::IntegerVector fem_ix_r, double rE, double rL, double rP, double rEIP, Rcpp::NumericVector muE_r, Rcpp::NumericVector muL_r, Rcpp::NumericVector muP_r, Rcpp::NumericVector muM_r, Rcpp::NumericVector muF_r, bool log_dd, Rcpp::NumericVector K_r, Rcpp::NumericVector gamma_dd_r, double beta, double nu, Rcpp::NumericVector omega_inv_r, Rcpp::NumericVector phi_r, Rcpp::NumericVector xiF_r, Rcpp::NumericVector xiM_r, Rcpp::NumericMatrix eta_r, Rcpp::NumericMatrix B_mat_r, bool has_move, Rcpp::NumericMatrix move_probs_r, Rcpp::NumericVector move_rates_r, Rcpp::NumericVector muM_node_base_r, Rcpp::NumericVector muF_node_base_r, double tol, Rcpp::Nullable<Rcpp::NumericVector> c_vec_r, Rcpp::Nullable<Rcpp::NumericVector> b_vec_r, Rcpp::NumericVector a_vec_r, double muH_param, double r_param, double delta_param, Rcpp::Nullable<Rcpp::NumericVector> cT_vec_r, Rcpp::Nullable<Rcpp::NumericVector> cD_vec_r, Rcpp::Nullable<Rcpp::NumericVector> cU_vec_r, Rcpp::Nullable<Rcpp::NumericVector> W_age_r, double d1, Rcpp::NumericVector fd_r, double ID0, double kd, double gamma1_imp, Rcpp::IntegerVector mosy_nodes_r, Rcpp::IntegerVector human_nodes_r, Rcpp::IntegerVector hS_ix_r, Rcpp::IntegerVector hI_ix_r, Rcpp::IntegerVector hE_ix_r, Rcpp::IntegerVector hR_ix_r, bool has_hmove, Rcpp::NumericMatrix h_move_probs_r, Rcpp::NumericVector h_move_rates_r, int nState);
RcppExport SEXP _malariasimulationGD_stoch_epi_engine_create(SEXP nNodesSEXP, SEXP nMSEXP, SEXP nGSEXP, SEXP nESEXP, SEXP nLSEXP, SEXP nPSEXP, SEXP nEIPSEXP, SEXP model_typeSEXP, SEXP egg_ix_rSEXP, SEXP larv_ix_rSEXP, SEXP pup_ix_rSEXP, SEXP male_ix_rSEXP, SEXP unm_ix_rSEXP, SEXP fem_ix_rSEXP, SEXP rESEXP, SEXP rLSEXP, SEXP rPSEXP, SEXP rEIPSEXP, SEXP muE_rSEXP, SEXP muL_rSEXP, SEXP muP_rSEXP, SEXP muM_rSEXP, SEXP muF_rSEXP, SEXP log_ddSEXP, SEXP K_rSEXP, SEXP gamma_dd_rSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP omega_inv_rSEXP, SEXP phi_rSEXP, SEXP xiF_rSEXP, SEXP xiM_rSEXP, SEXP eta_rSEXP, SEXP B_mat_rSEXP, SEXP has_moveSEXP, SEXP move_probs_rSEXP, SEXP move_rates_rSEXP, SEXP muM_node_base_rSEXP, SEXP muF_node_base_rSEXP, SEXP tolSEXP, SEXP c_vec_rSEXP, SEXP b_vec_rSEXP, SEXP a_vec_rSEXP, SEXP muH_paramSEXP, SEXP r_paramSEXP, SEXP delta_paramSEXP, SEXP cT_vec_rSEXP, SEXP cD_vec_rSEXP, SEXP cU_vec_rSEXP, SEXP W_age_rSEXP, SEXP d1SEXP, SEXP fd_rSEXP, SEXP ID0SEXP, SEXP kdSEXP, SEXP gamma1_impSEXP, SEXP mosy_nodes_rSEXP, SEXP human_nodes_rSEXP, SEXP hS_ix_rSEXP, SEXP hI_ix_rSEXP, SEXP hE_ix_rSEXP, SEXP hR_ix_rSEXP, SEXP has_hmoveSEXP, SEXP h_move_probs_rSEXP, SEXP h_move_rates_rSEXP, SEXP nStateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nNodes(nNodesSEXP);
    Rcpp::traits::input_parameter< int >::type nM(nMSEXP);
    Rcpp::traits::input_parameter< int >::type nG(nGSEXP);
    Rcpp::traits::input_parameter< int >::type nE(nESEXP);
    Rcpp::traits::input_parameter< int >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< int >::type nEIP(nEIPSEXP);
    Rcpp::traits::input_parameter< int >::type model_type(model_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type egg_ix_r(egg_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type larv_ix_r(larv_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type pup_ix_r(pup_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type male_ix_r(male_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type unm_ix_r(unm_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type fem_ix_r(fem_ix_rSEXP);
    Rcpp::traits::input_parameter< double >::type rE(rESEXP);
    Rcpp::traits::input_parameter< double >::type rL(rLSEXP);
    Rcpp::traits::input_parameter< double >::type rP(rPSEXP);
    Rcpp::traits::input_parameter< double >::type rEIP(rEIPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muE_r(muE_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muL_r(muL_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muP_r(muP_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muM_r(muM_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muF_r(muF_rSEXP);
    Rcpp::traits::input_parameter< bool >::type log_dd(log_ddSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type K_r(K_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_dd_r(gamma_dd_rSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type omega_inv_r(omega_inv_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type phi_r(phi_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xiF_r(xiF_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xiM_r(xiM_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type eta_r(eta_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B_mat_r(B_mat_rSEXP);
    Rcpp::traits::input_parameter< bool >::type has_move(has_moveSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type move_probs_r(move_probs_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type move_rates_r(move_rates_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muM_node_base_r(muM_node_base_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muF_node_base_r(muF_node_base_rSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type c_vec_r(c_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type b_vec_r(b_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_vec_r(a_vec_rSEXP);
    Rcpp::traits::input_parameter< double >::type muH_param(muH_paramSEXP);
    Rcpp::traits::input_parameter< double >::type r_param(r_paramSEXP);
    Rcpp::traits::input_parameter< double >::type delta_param(delta_paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cT_vec_r(cT_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cD_vec_r(cD_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cU_vec_r(cU_vec_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type W_age_r(W_age_rSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fd_r(fd_rSEXP);
    Rcpp::traits::input_parameter< double >::type ID0(ID0SEXP);
    Rcpp::traits::input_parameter< double >::type kd(kdSEXP);
    Rcpp::traits::input_parameter< double >::type gamma1_imp(gamma1_impSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type mosy_nodes_r(mosy_nodes_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type human_nodes_r(human_nodes_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hS_ix_r(hS_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hI_ix_r(hI_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hE_ix_r(hE_ix_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hR_ix_r(hR_ix_rSEXP);
    Rcpp::traits::input_parameter< bool >::type has_hmove(has_hmoveSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type h_move_probs_r(h_move_probs_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h_move_rates_r(h_move_rates_rSEXP);
    Rcpp::traits::input_parameter< int >::type nState(nStateSEXP);
    rcpp_result_gen = Rcpp::wrap(stoch_epi_engine_create(nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix_r, larv_ix_r, pup_ix_r, male_ix_r, unm_ix_r, fem_ix_r, rE, rL, rP, rEIP, muE_r, muL_r, muP_r, muM_r, muF_r, log_dd, K_r, gamma_dd_r, beta, nu, omega_inv_r, phi_r, xiF_r, xiM_r, eta_r, B_mat_r, has_move, move_probs_r, move_rates_r, muM_node_base_r, muF_node_base_r, tol, c_vec_r, b_vec_r, a_vec_r, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_r, h_move_rates_r, nState));
    return rcpp_result_gen;
END_RCPP
}
// stoch_epi_engine_set_seasonal
void stoch_epi_engine_set_seasonal(SEXP engine_ptr, int tmax, Rcpp::Nullable<Rcpp::NumericVector> beta_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> nu_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qE_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qL_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> qEIP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muE_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muL_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muP_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muM_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muF_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> K_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> gamma_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> a_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> muH_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> r_tbl_r, Rcpp::Nullable<Rcpp::NumericVector> delta_tbl_r);
RcppExport SEXP _malariasimulationGD_stoch_epi_engine_set_seasonal(SEXP engine_ptrSEXP, SEXP tmaxSEXP, SEXP beta_tbl_rSEXP, SEXP nu_tbl_rSEXP, SEXP qE_tbl_rSEXP, SEXP qL_tbl_rSEXP, SEXP qP_tbl_rSEXP, SEXP qEIP_tbl_rSEXP, SEXP muE_tbl_rSEXP, SEXP muL_tbl_rSEXP, SEXP muP_tbl_rSEXP, SEXP muM_tbl_rSEXP, SEXP muF_tbl_rSEXP, SEXP K_tbl_rSEXP, SEXP gamma_tbl_rSEXP, SEXP a_tbl_rSEXP, SEXP muH_tbl_rSEXP, SEXP r_tbl_rSEXP, SEXP delta_tbl_rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_tbl_r(beta_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type nu_tbl_r(nu_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qE_tbl_r(qE_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qL_tbl_r(qL_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qP_tbl_r(qP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type qEIP_tbl_r(qEIP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muE_tbl_r(muE_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muL_tbl_r(muL_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muP_tbl_r(muP_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muM_tbl_r(muM_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muF_tbl_r(muF_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type K_tbl_r(K_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type gamma_tbl_r(gamma_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type a_tbl_r(a_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type muH_tbl_r(muH_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type r_tbl_r(r_tbl_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type delta_tbl_r(delta_tbl_rSEXP);
    stoch_epi_engine_set_seasonal(engine_ptr, tmax, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r);
    return R_NilValue;
END_RCPP
}
// stoch_epi_engine_set_runtime
void stoch_epi_engine_set_runtime(SEXP engine_ptr, Rcpp::NumericVector beta_r, Rcpp::NumericVector muM_r, Rcpp::NumericVector muF_r, Rcpp::NumericVector K_r, Rcpp::NumericVector gamma_dd_r, Rcpp::NumericVector a_vec_r);
RcppExport SEXP _malariasimulationGD_stoch_epi_engine_set_runtime(SEXP engine_ptrSEXP, SEXP beta_rSEXP, SEXP muM_rSEXP, SEXP muF_rSEXP, SEXP K_rSEXP, SEXP gamma_dd_rSEXP, SEXP a_vec_rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_r(beta_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muM_r(muM_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type muF_r(muF_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type K_r(K_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma_dd_r(gamma_dd_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_vec_r(a_vec_rSEXP);
    stoch_epi_engine_set_runtime(engine_ptr, beta_r, muM_r, muF_r, K_r, gamma_dd_r, a_vec_r);
    return R_NilValue;
END_RCPP
}
// stoch_epi_engine_set_incidence
void stoch_epi_engine_set_incidence(SEXP engine_ptr, Rcpp::IntegerVector inc_ix_r);
RcppExport SEXP _malariasimulationGD_stoch_epi_engine_set_incidence(SEXP engine_ptrSEXP, SEXP inc_ix_rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type inc_ix_r(inc_ix_rSEXP);
    stoch_epi_engine_set_incidence(engine_ptr, inc_ix_r);
    return R_NilValue;
END_RCPP
}
// stoch_epi_set_human_state
void stoch_epi_set_human_state(SEXP engine_ptr, Rcpp::NumericVector h_state, int na);
RcppExport SEXP _malariasimulationGD_stoch_epi_set_human_state(SEXP engine_ptrSEXP, SEXP h_stateSEXP, SEXP naSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h_state(h_stateSEXP);
    Rcpp::traits::input_parameter< int >::type na(naSEXP);
    stoch_epi_set_human_state(engine_ptr, h_state, na);
    return R_NilValue;
END_RCPP
}
// stoch_epi_simulate
Rcpp::NumericMatrix stoch_epi_simulate(SEXP engine_ptr, Rcpp::NumericVector x0, double dt_stoch, double dt_out, double tmax);
RcppExport SEXP _malariasimulationGD_stoch_epi_simulate(SEXP engine_ptrSEXP, SEXP x0SEXP, SEXP dt_stochSEXP, SEXP dt_outSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type dt_stoch(dt_stochSEXP);
    Rcpp::traits::input_parameter< double >::type dt_out(dt_outSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(stoch_epi_simulate(engine_ptr, x0, dt_stoch, dt_out, tmax));
    return rcpp_result_gen;
END_RCPP
}
// stoch_epi_step_native
Rcpp::NumericVector stoch_epi_step_native(SEXP engine_ptr, Rcpp::NumericVector state_r, double t, double dt_stoch, double dt_out);
RcppExport SEXP _malariasimulationGD_stoch_epi_step_native(SEXP engine_ptrSEXP, SEXP state_rSEXP, SEXP tSEXP, SEXP dt_stochSEXP, SEXP dt_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type state_r(state_rSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type dt_stoch(dt_stochSEXP);
    Rcpp::traits::input_parameter< double >::type dt_out(dt_outSEXP);
    rcpp_result_gen = Rcpp::wrap(stoch_epi_step_native(engine_ptr, state_r, t, dt_stoch, dt_out));
    return rcpp_result_gen;
END_RCPP
}
// create_timeseries
Rcpp::XPtr<Timeseries> create_timeseries(size_t size, double default_value);
RcppExport SEXP _malariasimulationGD_create_timeseries(SEXP sizeSEXP, SEXP default_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type default_value(default_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(create_timeseries(size, default_value));
    return rcpp_result_gen;
END_RCPP
}
// timeseries_at
double timeseries_at(Rcpp::XPtr<Timeseries> timeseries, double timestep, bool linear);
RcppExport SEXP _malariasimulationGD_timeseries_at(SEXP timeseriesSEXP, SEXP timestepSEXP, SEXP linearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Timeseries> >::type timeseries(timeseriesSEXP);
    Rcpp::traits::input_parameter< double >::type timestep(timestepSEXP);
    Rcpp::traits::input_parameter< bool >::type linear(linearSEXP);
    rcpp_result_gen = Rcpp::wrap(timeseries_at(timeseries, timestep, linear));
    return rcpp_result_gen;
END_RCPP
}
// timeseries_push
void timeseries_push(Rcpp::XPtr<Timeseries> timeseries, double value, double timestep);
RcppExport SEXP _malariasimulationGD_timeseries_push(SEXP timeseriesSEXP, SEXP valueSEXP, SEXP timestepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Timeseries> >::type timeseries(timeseriesSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< double >::type timestep(timestepSEXP);
    timeseries_push(timeseries, value, timestep);
    return R_NilValue;
END_RCPP
}
// timeseries_save_state
Rcpp::List timeseries_save_state(Rcpp::XPtr<Timeseries> timeseries);
RcppExport SEXP _malariasimulationGD_timeseries_save_state(SEXP timeseriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Timeseries> >::type timeseries(timeseriesSEXP);
    rcpp_result_gen = Rcpp::wrap(timeseries_save_state(timeseries));
    return rcpp_result_gen;
END_RCPP
}
// timeseries_restore_state
void timeseries_restore_state(Rcpp::XPtr<Timeseries> timeseries, Rcpp::List state);
RcppExport SEXP _malariasimulationGD_timeseries_restore_state(SEXP timeseriesSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<Timeseries> >::type timeseries(timeseriesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type state(stateSEXP);
    timeseries_restore_state(timeseries, state);
    return R_NilValue;
END_RCPP
}
// random_seed
void random_seed(size_t seed);
RcppExport SEXP _malariasimulationGD_random_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type seed(seedSEXP);
    random_seed(seed);
    return R_NilValue;
END_RCPP
}
// random_save_state
std::string random_save_state();
RcppExport SEXP _malariasimulationGD_random_save_state() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(random_save_state());
    return rcpp_result_gen;
END_RCPP
}
// random_restore_state
void random_restore_state(std::string state);
RcppExport SEXP _malariasimulationGD_random_restore_state(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type state(stateSEXP);
    random_restore_state(state);
    return R_NilValue;
END_RCPP
}
// bernoulli_multi_p_cpp
std::vector<size_t> bernoulli_multi_p_cpp(const std::vector<double> p);
RcppExport SEXP _malariasimulationGD_bernoulli_multi_p_cpp(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(bernoulli_multi_p_cpp(p));
    return rcpp_result_gen;
END_RCPP
}
// bitset_index_cpp
std::vector<size_t> bitset_index_cpp(Rcpp::XPtr<individual_index_t> a, Rcpp::XPtr<individual_index_t> b);
RcppExport SEXP _malariasimulationGD_bitset_index_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<individual_index_t> >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<individual_index_t> >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(bitset_index_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_weighted_sample
Rcpp::IntegerVector fast_weighted_sample(size_t size, std::vector<double> probs);
RcppExport SEXP _malariasimulationGD_fast_weighted_sample(SEXP sizeSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< size_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_weighted_sample(size, probs));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(void);

static const R_CallMethodDef CallEntries[] = {
    {"_malariasimulationGD_create_adult_mosquito_model", (DL_FUNC) &_malariasimulationGD_create_adult_mosquito_model, 5},
    {"_malariasimulationGD_adult_mosquito_model_update", (DL_FUNC) &_malariasimulationGD_adult_mosquito_model_update, 5},
    {"_malariasimulationGD_adult_mosquito_model_save_state", (DL_FUNC) &_malariasimulationGD_adult_mosquito_model_save_state, 1},
    {"_malariasimulationGD_adult_mosquito_model_restore_state", (DL_FUNC) &_malariasimulationGD_adult_mosquito_model_restore_state, 2},
    {"_malariasimulationGD_create_adult_solver", (DL_FUNC) &_malariasimulationGD_create_adult_solver, 5},
    {"_malariasimulationGD_create_aquatic_mosquito_model", (DL_FUNC) &_malariasimulationGD_create_aquatic_mosquito_model, 18},
    {"_malariasimulationGD_aquatic_mosquito_model_update", (DL_FUNC) &_malariasimulationGD_aquatic_mosquito_model_update, 4},
    {"_malariasimulationGD_aquatic_mosquito_model_set_egg_proportions", (DL_FUNC) &_malariasimulationGD_aquatic_mosquito_model_set_egg_proportions, 2},
    {"_malariasimulationGD_create_aquatic_solver", (DL_FUNC) &_malariasimulationGD_create_aquatic_solver, 5},
    {"_malariasimulationGD_ento_engine_create", (DL_FUNC) &_malariasimulationGD_ento_engine_create, 37},
    {"_malariasimulationGD_ento_engine_set_runtime", (DL_FUNC) &_malariasimulationGD_ento_engine_set_runtime, 6},
    {"_malariasimulationGD_ento_engine_set_seasonal_K", (DL_FUNC) &_malariasimulationGD_ento_engine_set_seasonal_K, 3},
    {"_malariasimulationGD_ento_engine_dxdt", (DL_FUNC) &_malariasimulationGD_ento_engine_dxdt, 3},
    {"_malariasimulationGD_create_ento_solver", (DL_FUNC) &_malariasimulationGD_create_ento_solver, 5},
    {"_malariasimulationGD_ento_engine_set_native", (DL_FUNC) &_malariasimulationGD_ento_engine_set_native, 1},
    {"_malariasimulationGD_ento_engine_clear_native", (DL_FUNC) &_malariasimulationGD_ento_engine_clear_native, 0},
    {"_malariasimulationGD_epi_engine_create", (DL_FUNC) &_malariasimulationGD_epi_engine_create, 65},
    {"_malariasimulationGD_epi_engine_set_seasonal", (DL_FUNC) &_malariasimulationGD_epi_engine_set_seasonal, 19},
    {"_malariasimulationGD_epi_engine_set_native", (DL_FUNC) &_malariasimulationGD_epi_engine_set_native, 1},
    {"_malariasimulationGD_epi_engine_clear_native", (DL_FUNC) &_malariasimulationGD_epi_engine_clear_native, 0},
    {"_malariasimulationGD_epi_engine_set_runtime", (DL_FUNC) &_malariasimulationGD_epi_engine_set_runtime, 7},
    {"_malariasimulationGD_epi_engine_set_human_state", (DL_FUNC) &_malariasimulationGD_epi_engine_set_human_state, 2},
    {"_malariasimulationGD_epi_engine_dxdt", (DL_FUNC) &_malariasimulationGD_epi_engine_dxdt, 3},
    {"_malariasimulationGD_create_epi_solver", (DL_FUNC) &_malariasimulationGD_create_epi_solver, 5},
    {"_malariasimulationGD_carrying_capacity", (DL_FUNC) &_malariasimulationGD_carrying_capacity, 8},
    {"_malariasimulationGD_eggs_laid", (DL_FUNC) &_malariasimulationGD_eggs_laid, 3},
    {"_malariasimulationGD_rainfall", (DL_FUNC) &_malariasimulationGD_rainfall, 5},
    {"_malariasimulationGD_exponential_process_cpp", (DL_FUNC) &_malariasimulationGD_exponential_process_cpp, 2},
    {"_malariasimulationGD_solver_get_states", (DL_FUNC) &_malariasimulationGD_solver_get_states, 1},
    {"_malariasimulationGD_solver_set_states", (DL_FUNC) &_malariasimulationGD_solver_set_states, 3},
    {"_malariasimulationGD_solver_step", (DL_FUNC) &_malariasimulationGD_solver_step, 1},
    {"_malariasimulationGD_stoch_epi_engine_create", (DL_FUNC) &_malariasimulationGD_stoch_epi_engine_create, 65},
    {"_malariasimulationGD_stoch_epi_engine_set_seasonal", (DL_FUNC) &_malariasimulationGD_stoch_epi_engine_set_seasonal, 19},
    {"_malariasimulationGD_stoch_epi_engine_set_runtime", (DL_FUNC) &_malariasimulationGD_stoch_epi_engine_set_runtime, 7},
    {"_malariasimulationGD_stoch_epi_engine_set_incidence", (DL_FUNC) &_malariasimulationGD_stoch_epi_engine_set_incidence, 2},
    {"_malariasimulationGD_stoch_epi_set_human_state", (DL_FUNC) &_malariasimulationGD_stoch_epi_set_human_state, 3},
    {"_malariasimulationGD_stoch_epi_simulate", (DL_FUNC) &_malariasimulationGD_stoch_epi_simulate, 5},
    {"_malariasimulationGD_stoch_epi_step_native", (DL_FUNC) &_malariasimulationGD_stoch_epi_step_native, 5},
    {"_malariasimulationGD_create_timeseries", (DL_FUNC) &_malariasimulationGD_create_timeseries, 2},
    {"_malariasimulationGD_timeseries_at", (DL_FUNC) &_malariasimulationGD_timeseries_at, 3},
    {"_malariasimulationGD_timeseries_push", (DL_FUNC) &_malariasimulationGD_timeseries_push, 3},
    {"_malariasimulationGD_timeseries_save_state", (DL_FUNC) &_malariasimulationGD_timeseries_save_state, 1},
    {"_malariasimulationGD_timeseries_restore_state", (DL_FUNC) &_malariasimulationGD_timeseries_restore_state, 2},
    {"_malariasimulationGD_random_seed", (DL_FUNC) &_malariasimulationGD_random_seed, 1},
    {"_malariasimulationGD_random_save_state", (DL_FUNC) &_malariasimulationGD_random_save_state, 0},
    {"_malariasimulationGD_random_restore_state", (DL_FUNC) &_malariasimulationGD_random_restore_state, 1},
    {"_malariasimulationGD_bernoulli_multi_p_cpp", (DL_FUNC) &_malariasimulationGD_bernoulli_multi_p_cpp, 1},
    {"_malariasimulationGD_bitset_index_cpp", (DL_FUNC) &_malariasimulationGD_bitset_index_cpp, 2},
    {"_malariasimulationGD_fast_weighted_sample", (DL_FUNC) &_malariasimulationGD_fast_weighted_sample, 2},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 0},
    {NULL, NULL, 0}
};

void register_ento_native_routines(DllInfo* dll);
RcppExport void R_init_malariasimulationGD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    register_ento_native_routines(dll);
}
