# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_adult_mosquito_model <- function(growth_model, mu, tau, susceptible, foim) {
    .Call(`_malariasimulationGD_create_adult_mosquito_model`, growth_model, mu, tau, susceptible, foim)
}

adult_mosquito_model_update <- function(model, mu, foim, susceptible, f) {
    invisible(.Call(`_malariasimulationGD_adult_mosquito_model_update`, model, mu, foim, susceptible, f))
}

adult_mosquito_model_save_state <- function(model) {
    .Call(`_malariasimulationGD_adult_mosquito_model_save_state`, model)
}

adult_mosquito_model_restore_state <- function(model, state) {
    invisible(.Call(`_malariasimulationGD_adult_mosquito_model_restore_state`, model, state))
}

create_adult_solver <- function(model, init, r_tol, a_tol, max_steps) {
    .Call(`_malariasimulationGD_create_adult_solver`, model, init, r_tol, a_tol, max_steps)
}

create_aquatic_mosquito_model <- function(beta, de, mue, k_timeseries, gamma, dl, mul, dp, mup, total_M, model_seasonality, g0, g, h, R_bar, mum, f, rainfall_floor) {
    .Call(`_malariasimulationGD_create_aquatic_mosquito_model`, beta, de, mue, k_timeseries, gamma, dl, mul, dp, mup, total_M, model_seasonality, g0, g, h, R_bar, mum, f, rainfall_floor)
}

aquatic_mosquito_model_update <- function(model, total_M, f, mum) {
    invisible(.Call(`_malariasimulationGD_aquatic_mosquito_model_update`, model, total_M, f, mum))
}

aquatic_mosquito_model_set_egg_proportions <- function(model, egg_proportions) {
    invisible(.Call(`_malariasimulationGD_aquatic_mosquito_model_set_egg_proportions`, model, egg_proportions))
}

create_aquatic_solver <- function(model, init, r_tol, a_tol, max_steps) {
    .Call(`_malariasimulationGD_create_aquatic_solver`, model, init, r_tol, a_tol, max_steps)
}

ento_engine_create <- function(nNodes, nG, nE, nL, nP, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix, rE, rL, rP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, nState) {
    .Call(`_malariasimulationGD_ento_engine_create`, nNodes, nG, nE, nL, nP, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix, rE, rL, rP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, nState)
}

ento_engine_set_runtime <- function(engine_ptr, beta_vec, muM, muF, K, gamma_dd) {
    invisible(.Call(`_malariasimulationGD_ento_engine_set_runtime`, engine_ptr, beta_vec, muM, muF, K, gamma_dd))
}

ento_engine_set_seasonal_K <- function(engine_ptr, tmax_seasonal, K_tbl_r) {
    invisible(.Call(`_malariasimulationGD_ento_engine_set_seasonal_K`, engine_ptr, tmax_seasonal, K_tbl_r))
}

ento_engine_dxdt <- function(engine_ptr, t, state) {
    .Call(`_malariasimulationGD_ento_engine_dxdt`, engine_ptr, t, state)
}

create_ento_solver <- function(engine_ptr, init, r_tol, a_tol, max_steps) {
    .Call(`_malariasimulationGD_create_ento_solver`, engine_ptr, init, r_tol, a_tol, max_steps)
}

ento_engine_set_native <- function(engine_ptr) {
    invisible(.Call(`_malariasimulationGD_ento_engine_set_native`, engine_ptr))
}

ento_engine_clear_native <- function() {
    invisible(.Call(`_malariasimulationGD_ento_engine_clear_native`))
}

epi_engine_create <- function(nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix_flat, rE, rL, rP, rEIP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, c_vec_r, b_vec_r, a_vec, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_dense, h_move_rates, nState) {
    .Call(`_malariasimulationGD_epi_engine_create`, nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix, larv_ix, pup_ix, male_ix, unm_ix, fem_ix_flat, rE, rL, rP, rEIP, muE, muL, muP, muM, muF, log_dd, K, gamma_dd, beta, nu, omega, phi_cube, xiF, xiM, eta, B_mat, has_move, move_probs_dense, move_rates, muM_node_base, muF_node_base, tol, c_vec_r, b_vec_r, a_vec, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_dense, h_move_rates, nState)
}

epi_engine_set_seasonal <- function(engine_ptr, tmax_seasonal, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r) {
    invisible(.Call(`_malariasimulationGD_epi_engine_set_seasonal`, engine_ptr, tmax_seasonal, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r))
}

epi_engine_set_native <- function(engine_ptr) {
    invisible(.Call(`_malariasimulationGD_epi_engine_set_native`, engine_ptr))
}

epi_engine_clear_native <- function() {
    invisible(.Call(`_malariasimulationGD_epi_engine_clear_native`))
}

epi_engine_set_runtime <- function(engine_ptr, beta, muM, muF, K, gamma_dd, a_vec) {
    invisible(.Call(`_malariasimulationGD_epi_engine_set_runtime`, engine_ptr, beta, muM, muF, K, gamma_dd, a_vec))
}

epi_engine_set_human_state <- function(h_state, na) {
    invisible(.Call(`_malariasimulationGD_epi_engine_set_human_state`, h_state, na))
}

epi_engine_dxdt <- function(engine_ptr, t, state) {
    .Call(`_malariasimulationGD_epi_engine_dxdt`, engine_ptr, t, state)
}

create_epi_solver <- function(engine_ptr, init, r_tol, a_tol, max_steps) {
    .Call(`_malariasimulationGD_create_epi_solver`, engine_ptr, init, r_tol, a_tol, max_steps)
}

carrying_capacity <- function(timestep, model_seasonality, g0, g, h, K0, R_bar, rainfall_floor) {
    .Call(`_malariasimulationGD_carrying_capacity`, timestep, model_seasonality, g0, g, h, K0, R_bar, rainfall_floor)
}

eggs_laid <- function(beta, mu, f) {
    .Call(`_malariasimulationGD_eggs_laid`, beta, mu, f)
}

rainfall <- function(t, g0, g, h, floor) {
    .Call(`_malariasimulationGD_rainfall`, t, g0, g, h, floor)
}

exponential_process_cpp <- function(variable, rate) {
    .Call(`_malariasimulationGD_exponential_process_cpp`, variable, rate)
}

solver_get_states <- function(solver) {
    .Call(`_malariasimulationGD_solver_get_states`, solver)
}

solver_set_states <- function(solver, t, state) {
    invisible(.Call(`_malariasimulationGD_solver_set_states`, solver, t, state))
}

solver_step <- function(solver) {
    invisible(.Call(`_malariasimulationGD_solver_step`, solver))
}

stoch_epi_engine_create <- function(nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix_r, larv_ix_r, pup_ix_r, male_ix_r, unm_ix_r, fem_ix_r, rE, rL, rP, rEIP, muE_r, muL_r, muP_r, muM_r, muF_r, log_dd, K_r, gamma_dd_r, beta, nu, omega_inv_r, phi_r, xiF_r, xiM_r, eta_r, B_mat_r, has_move, move_probs_r, move_rates_r, muM_node_base_r, muF_node_base_r, tol, c_vec_r, b_vec_r, a_vec_r, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_r, h_move_rates_r, nState) {
    .Call(`_malariasimulationGD_stoch_epi_engine_create`, nNodes, nM, nG, nE, nL, nP, nEIP, model_type, egg_ix_r, larv_ix_r, pup_ix_r, male_ix_r, unm_ix_r, fem_ix_r, rE, rL, rP, rEIP, muE_r, muL_r, muP_r, muM_r, muF_r, log_dd, K_r, gamma_dd_r, beta, nu, omega_inv_r, phi_r, xiF_r, xiM_r, eta_r, B_mat_r, has_move, move_probs_r, move_rates_r, muM_node_base_r, muF_node_base_r, tol, c_vec_r, b_vec_r, a_vec_r, muH_param, r_param, delta_param, cT_vec_r, cD_vec_r, cU_vec_r, W_age_r, d1, fd_r, ID0, kd, gamma1_imp, mosy_nodes_r, human_nodes_r, hS_ix_r, hI_ix_r, hE_ix_r, hR_ix_r, has_hmove, h_move_probs_r, h_move_rates_r, nState)
}

stoch_epi_engine_set_seasonal <- function(engine_ptr, tmax, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r) {
    invisible(.Call(`_malariasimulationGD_stoch_epi_engine_set_seasonal`, engine_ptr, tmax, beta_tbl_r, nu_tbl_r, qE_tbl_r, qL_tbl_r, qP_tbl_r, qEIP_tbl_r, muE_tbl_r, muL_tbl_r, muP_tbl_r, muM_tbl_r, muF_tbl_r, K_tbl_r, gamma_tbl_r, a_tbl_r, muH_tbl_r, r_tbl_r, delta_tbl_r))
}

stoch_epi_engine_set_runtime <- function(engine_ptr, beta_r, muM_r, muF_r, K_r, gamma_dd_r, a_vec_r) {
    invisible(.Call(`_malariasimulationGD_stoch_epi_engine_set_runtime`, engine_ptr, beta_r, muM_r, muF_r, K_r, gamma_dd_r, a_vec_r))
}

stoch_epi_engine_set_incidence <- function(engine_ptr, inc_ix_r) {
    invisible(.Call(`_malariasimulationGD_stoch_epi_engine_set_incidence`, engine_ptr, inc_ix_r))
}

stoch_epi_set_human_state <- function(engine_ptr, h_state, na) {
    invisible(.Call(`_malariasimulationGD_stoch_epi_set_human_state`, engine_ptr, h_state, na))
}

stoch_epi_simulate <- function(engine_ptr, x0, dt_stoch, dt_out, tmax) {
    .Call(`_malariasimulationGD_stoch_epi_simulate`, engine_ptr, x0, dt_stoch, dt_out, tmax)
}

stoch_epi_step_native <- function(engine_ptr, state_r, t, dt_stoch, dt_out) {
    .Call(`_malariasimulationGD_stoch_epi_step_native`, engine_ptr, state_r, t, dt_stoch, dt_out)
}

create_timeseries <- function(size, default_value) {
    .Call(`_malariasimulationGD_create_timeseries`, size, default_value)
}

timeseries_at <- function(timeseries, timestep, linear) {
    .Call(`_malariasimulationGD_timeseries_at`, timeseries, timestep, linear)
}

timeseries_push <- function(timeseries, value, timestep) {
    invisible(.Call(`_malariasimulationGD_timeseries_push`, timeseries, value, timestep))
}

timeseries_save_state <- function(timeseries) {
    .Call(`_malariasimulationGD_timeseries_save_state`, timeseries)
}

timeseries_restore_state <- function(timeseries, state) {
    invisible(.Call(`_malariasimulationGD_timeseries_restore_state`, timeseries, state))
}

random_seed <- function(seed) {
    invisible(.Call(`_malariasimulationGD_random_seed`, seed))
}

random_save_state <- function() {
    .Call(`_malariasimulationGD_random_save_state`)
}

random_restore_state <- function(state) {
    invisible(.Call(`_malariasimulationGD_random_restore_state`, state))
}

bernoulli_multi_p_cpp <- function(p) {
    .Call(`_malariasimulationGD_bernoulli_multi_p_cpp`, p)
}

bitset_index_cpp <- function(a, b) {
    .Call(`_malariasimulationGD_bitset_index_cpp`, a, b)
}

fast_weighted_sample <- function(size, probs) {
    .Call(`_malariasimulationGD_fast_weighted_sample`, size, probs)
}

